### PR TITLE
Luthfir/discord notification

### PR DESCRIPTION
**Pull request by luthfir-rahman**
# Description

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist
- [ ] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [ ] I have performed a self-review of my own code
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] If new documentation has been added, relative paths have been added to the appropriate section of `docs/mint.json`

cc:

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
Could you fix the code style issue? You can set up pre-commit hook locally: https://github.com/mage-ai/mage-ai/blob/master/README_dev.md

**Review by wangxiaoyou1993 — COMMENTED** [review]
Could you also add a doc for discord channel and include instruction of getting the webhook_url?
Example doc:
https://github.com/mage-ai/mage-ai/blob/master/docs/integrations/observability/alerting-slack.mdx

**Comment by wangxiaoyou1993** [comment]
We can merge the PR after the doc is added

**Comment by wangxiaoyou1993** [comment]
Also have you tested this change locally?

**Comment by luthfir-rahman** [comment]
> Could you also add a doc for discord channel and include instruction of getting the webhook_url? Example doc: https://github.com/mage-ai/mage-ai/blob/master/docs/integrations/observability/alerting-slack.mdx

already add the mdx file ya @wangxiaoyou1993

**Pull request merged**
