### PR TITLE
Automatically open app in a new tab using default browser

### PR DESCRIPTION
**Pull request by bruno-uy**
# Summary
When the app starts listening in the defined `host:port`, a new tab on the default browser is opened.

Solves #2233. It doesn't work with Docker, and the explanation is in the issue's comments.

# Tests
Tested locally with MacOS/Chrome, but since it's a standard library from Python, it shouldn't have any issues with other OS/browser.

### CODE REVIEW

**Comment by tommydangerous** [comment]
Looking 👀

**Comment by bruno-uy** [comment]
The Walrus operator (`:=`) is supported starting in Python 3.8, and I realized mage also supports Python 3.7. @tommydangerous I have another commit ready to change that to a standard variable assignment. Let me know if we want 3.7 support, and I can push it.

**Comment by wangxiaoyou1993** [comment]
Hey @bruno-uy , we do want to support 3.7.

**Review by wangxiaoyou1993 — APPROVED** [review]

**Comment by wangxiaoyou1993** [comment]
Thanks you @bruno-uy for contributing to Mage and solve that github issue!

**Pull request merged**
