### PR TITLE
[dy] Add script to run postgres locally in docker

### PR DESCRIPTION
**Pull request by dy46**
# Summary

Add commands to setup doc to create a postgresql docker container and connect to it.

# Tests

tested locally

cc: @wangxiaoyou1993

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
For users who run Mage locally, they don't use docker-compose.

**Comment by dy46** [comment]
@wangxiaoyou1993 do we just want them to run another command to start postgres locally then?

**Comment by wangxiaoyou1993** [comment]
> @wangxiaoyou1993 do we just want them to run another command to start postgres locally then?

Yes, and be able to connect to postgres.

**Comment by dy46** [comment]
@wangxiaoyou1993 updated

**Review by wangxiaoyou1993 — APPROVED** [review]

**Pull request merged**
