### PR TITLE
Docker: Optimize build by reordering and grouping some statements

### PR DESCRIPTION
**Pull request by christopherscholz**
# Description
Resolves: #3248
Groupes and Reorders Docker Statements for better build performance
- lower number of layers (smaller build)
- often changing things last

# How Has This Been Tested?
- [x] Ran Dockerfile
- [x] Ran dev.Dockerfile with scripts/dev.sh

# Checklist
- [x] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [x] I have performed a self-review of my own code
- [x] I have added unit tests that prove my fix is effective or that my feature works; not needed
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation; not needed

cc: @wangxiaoyou1993

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
cc: @dy46

**Comment by dy46** [comment]
thanks for doing this @christopherscholz! how did you determine the package versions to install?

**Comment by christopherscholz** [comment]
> thanks for doing this @christopherscholz! how did you determine the package versions to install?

I just checked at runtime. Once for amd64 and arm64. Both seem to use the same versions
```bash
apt list --installed
pip list
```

**Review by dy46 — APPROVED** [review]

**Comment by dy46** [comment]
Hey I reverted this PR because the docker build was failing for someone on the team due to version not exists errors. I'll try testing it a bit more, but just wanted to let you know why it was reverted.

**Pull request merged**
