### PR TITLE
Kafka source and sink include metadata

### LINKED ISSUE #2707: KafkaSource: publish timestamp and key
**Is your feature request related to a problem? Please describe.**
We are storing information in kafka messages using the key, value and timestamp fields. The current implementation of KafkaSource only publishes the value.

**Describe the solution you'd like**
We would like to get all the kafka message information, including key, value and timestamp.

**Describe alternatives you've considered**
Streaming pipelines are very restricted. We can't find an easy way to implement custom data loaders in python. 

**Additional context**
In [kafka.py:125](https://github.com/mage-ai/mage-ai/blob/b5039e3301d34a28355eb7af2410c31219f7b886/mage_ai/streaming/sources/kafka.py#LL125C13-L125C61) there may be a possibility to extend the message properties published.

### PR DESCRIPTION
**Pull request by mazieb**
# Description
Added metadata to kafka source and sink. Message schema compatible with #3378. Closes #2707.

# How Has This Been Tested?
- [x] Tested Locally

# Checklist
- [ ] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [x] I have performed a self-review of my own code
- [x] I have added unit tests that prove my fix is effective or that my feature works
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

cc:
@wangxiaoyou1993

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
Let's add another field `include_metadata` to the source config so that we can make it backward compatible.

**Comment by mazieb** [comment]
Added field `include_metadata` to the source config and made the default backward compatible.

**Review by wangxiaoyou1993 — APPROVED** [review]

**Comment by GitifyMe** [comment]
As much as I like the improvement, I have two additions that I think would be worth considering:
a) Expose the key from the message - partition is often not as useful as the key of the original message so that the same ordering constraints can be reused later
b) Ability to subscribe in multiple topics - now that the topic is exposed through the meta data, more advanced scenarios can be implemented and there might be multiple topics to source from.
c) How can the bootstrap server, the topics, the schema registry url  in the yaml configuration be parameterised?

**Comment by wangxiaoyou1993** [comment]
Hi @GitifyMe , some of your additions are addressed in this PR: https://github.com/mage-ai/mage-ai/pull/3532
Could you check whether that address your requests?

**Comment by GitifyMe** [comment]
Yes, the changes look good for b) ! Thanks for pointing this out...

**Pull request merged**
