### PR TITLE
WIP: Feat/gcs storage

### PR DESCRIPTION
**Pull request by luizarvo**
# Description

This MR enables using Google Cloud Storage as a variables storage (block outputs) the same way as S3 can be used.

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist
- [ ] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [ ] I have performed a self-review of my own code
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

cc:

### CODE REVIEW

**Comment by luizarvo** [comment]
> @luizarvo Thank you adding the GCS storage!!! Could you also fix the code quality check errors? You can install the pre-commit hooks in your development environment: https://github.com/mage-ai/mage-ai/blob/master/README_dev.md

Sure mate =)

**Comment by luizarvo** [comment]
PTAL? @wangxiaoyou1993

**Comment by wangxiaoyou1993** [comment]
@luizarvo did you test this PR?

**Comment by luizarvo** [comment]
> @luizarvo did you test this PR?

You mean manually? I actually did. I am using this code version on my mage deployment. Didn't test with spark yet though (which is the main reason why I implemented it actually). I'm running a pipeline to ETL a specific table from BigQuery to a database in production with this code (and using GCS to store variables of course)

**Review by wangxiaoyou1993 — APPROVED** [review]

**Pull request merged**
