### PR TITLE
Initialize google cloud storage source

### LINKED ISSUE #5000: Add Google Cloud Storage (GCS) as a data integration source
GCS is a commonly used object storage service, and especially for users working within the Google Cloud Platform it's frequently relied on for data exports/integrations with 3rd party platforms. If GCS data integration is enabled in Mage, it would open up a lot of use cases for various data pipelines and would be a huge benefit for GCP users.

### PR DESCRIPTION
**Pull request by TalaatHasanin**
# Description
Initialize google cloud storage source for data integration piplines. Fix #5000 

# How Has This Been Tested?

- [x] Test google cloud storage source

# Checklist
- [X] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [X] I have performed a self-review of my own code
- [X] I have added unit tests that prove my fix is effective or that my feature works
- [x] I have made corresponding changes to the documentation

cc:
@dy46 @wangxiaoyou1993

### CODE REVIEW

**Comment by TalaatHasanin** [comment]
Can I have a review on this? @wangxiaoyou1993 @dy46 
I tested the new source but when I pass the following argument it add all streams to the `test_catalog.json `
`--selected_streams '["commits"]' > mage_integrations/TEST_CATALOG.json`

**Review by wangxiaoyou1993 — COMMENTED** [review]
Can you include some screenshots about your UI testing?

**Comment by TalaatHasanin** [comment]
UI tests

Screenshot 2024-08-16 024107

Screenshot 2024-08-16 024142

Screenshot 2024-08-16 024230

**Comment by wangxiaoyou1993** [comment]
so from the implementation, it basically just syncs all the objects in the bucket: https://github.com/mage-ai/mage-ai/pull/5334/files#diff-66b46e7665bb98bb5e0155856e4ae881c61f5c772123767067498fcf9ba3a7a7R110-R121

**Comment by TalaatHasanin** [comment]
What I have to do? @wangxiaoyou1993

**Comment by wangxiaoyou1993** [comment]
> What I have to do? @wangxiaoyou1993

You can filter the blobs by your stream name

**Comment by TalaatHasanin** [comment]
Added `prefix` to filter the blobs based on it, but if not included, it will sync all blobs
Screenshot 2024-09-07 122418

@wangxiaoyou1993

**Review by wangxiaoyou1993 — APPROVED** [review]

**Pull request merged**
