### PR TITLE
Add kafka api_version to the data loader and data exporter templates

### PR DESCRIPTION
**Pull request by shrutimantri**
# Description
Added kafka api_version to the data loader and data exporter templates, updated the docs to incorporate this accordingly.

# How Has This Been Tested?

- [ Yes ] Made changes to data preparation test accordingly
- [ N/A ] Test B

# Checklist
- [ Yes ] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [ Yes ] I have performed a self-review of my own code
- [ N/A ] I have added unit tests that prove my fix is effective or that my feature works
- [ N/A ] I have commented my code, particularly in hard-to-understand areas
- [ Yes ] I have made corresponding changes to the documentation
- [ N/A ] If new documentation has been added, relative paths have been added to the appropriate section of `docs/mint.json`

cc:

### CODE REVIEW

**Comment by mazieb** [comment]
Just a small note:

We are not using confluent kafka but redpanda kafka and have to use api_version: "0.11.1" (https://docs.redpanda.com/current/develop/kafka-clients/#kafka-client-compatibility)

**Comment by shrutimantri** [comment]
> Just a small note:
> 
> We are not using confluent kafka but redpanda kafka and have to use api_version: "0.11.1" (https://docs.redpanda.com/current/develop/kafka-clients/#kafka-client-compatibility)

For any API version that you want to use, you can pass that api_version in the config, sounds good?

**Comment by mazieb** [comment]
> For any API version that you want to use, you can pass that api_version in the config, sounds good? 

Yeah, I know that now ;-)
I just thought that documenting this might help others with the same problem.

**Comment by shrutimantri** [comment]
> > For any API version that you want to use, you can pass that api_version in the config, sounds good?
> 
> Yeah, I know that now ;-) I just thought that documenting this might help others with the same problem.

Now I get the confusion, adding it explicitly to the template.

**Review by wangxiaoyou1993 — APPROVED** [review]

**Pull request merged**
