### PR TITLE
[dy] Add timeout for fetching files for git

### PR DESCRIPTION
**Pull request by dy46**
# Summary

Added a 10 second timeout for fetching untracked and staged files. The modified files call is a bit trickier to add a timeout for, but I think the main issue is the untracked files anyway.

# Tests

tested locally

cc:

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
Did you test creating 10k folders locally and checking the latency of the request?

**Comment by dy46** [comment]
@wangxiaoyou1993 I didn't try with 10000 folders, but I did test that it times out correctly after 10 seconds.

**Comment by wangxiaoyou1993** [comment]
Can you try creating 10k folders locally and see if Mage app can function correctly with it?

**Comment by dy46** [comment]
@wangxiaoyou1993 I created the folders, and everything seemed ok. The latency of the request is still around 10 seconds

**Review by wangxiaoyou1993 — APPROVED** [review]

**Pull request merged**
