### PR TITLE
Support TIMESTAMP in redshift convert

### PR DESCRIPTION
**Pull request by RobinFrcd**
Fix https://github.com/mage-ai/mage-ai/issues/3566

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
Have you tested this change?

**Comment by RobinFrcd** [comment]
@wangxiaoyou1993 
I've tested up to 
```
[(
    col,
    convert_python_type_to_redshift_type(
        convert_pandas_dtype_to_python_type(df.dtypes[col]),
    ),
) for col in columns]
```

And it works fine. I've also checked the [documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_Datetime_types.html#r_Datetime_types-timestamp) and TIMESTAMP seems to be what we needed.
However, doing and e2e test on my environment with redshift is not that easy so I didn't do a full test, no, sorry.

**Comment by wangxiaoyou1993** [comment]
@Luishfs will help test out this change.

**Review by wangxiaoyou1993 — APPROVED** [review]
I've tested this change. It works.

**Pull request merged**
