### PR TITLE
[sg] Filter pipeline runs by status

### PR DESCRIPTION
**Pull request by soumojit**
# Summary
> Added a query parameter called "status"
> URI -- /api/pipeline_runs?_limit=30&_offset=0&status=failed
> Added a filter for filtering results by "status" in process_pipeline_runs( )

# Tests
> Needs further testing on all possible status values

cc:
@tommydangerous @wangxiaoyou1993

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
Thank you @soumojit ! Could you also update the ApiPipelineRunListHandler to use the status filter?
Regarding testing, you can test the API locally with the steps
* Run server locally with `./scripts/dev.sh repo_name` or `./scripts/start.sh repo_name`
* Call endpoint `http://localhost:6789/api/pipeline_runs?status=completed` or `http://localhost:6789/api/pipeline_schedules/[schedule_id]/pipeline_runs?status=failed`. You can test these status values: https://github.com/mage-ai/mage-ai/blob/master/mage_ai/orchestration/db/models.py#L188-L193

**Comment by soumojit** [comment]
@wangxiaoyou1993 updated, please take a look.

**Review by wangxiaoyou1993 — APPROVED** [review]
Looks good after testing!

**Comment by wangxiaoyou1993** [comment]
@soumojit I just tested your PR. It works well. So I'm going to merge it.

**Comment by soumojit** [comment]
@wangxiaoyou1993 sorry, i was unable to respond yesterday. Yes, I had tested this. Thanks for merging!

**Pull request merged**
