### PR TITLE
Removed unused config in Salesforce destination

### PR DESCRIPTION
**Pull request by Luishfs**
# Description

Removed `is_sandbox` config

# How Has This Been Tested?

Tested on a local mage instance
Screenshot from 2023-08-16 01-24-27

# Checklist
- [X] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

cc:
@wangxiaoyou1993

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
I tested on the salesforce destination.
One issue is the config template doesn't show in the UI.
image

Can you update this import path to be absolute path and make sure the config template show in the UI? 
https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/destinations/salesforce/target_salesforce/target.py#L11

**Comment by wangxiaoyou1993** [comment]
And the "Test connection" is not supported for the Salesforce destination, which could causes the NoneType error.
Could you put up a fix similar with this PR https://github.com/mage-ai/mage-ai/pull/3158?

**Review by wangxiaoyou1993 — APPROVED** [review]

**Comment by PSmythOI** [comment]
Hi, just wanted to follow up on your comment about the config template. It still does not show up in the UI for me, just as you showed in the picture above.

**Comment by wangxiaoyou1993** [comment]
Hi @PSmythOI , are you using the latest version of Mage?
You should be able to see the config template in UI in latest versin
image

**Comment by PSmythOI** [comment]
I updated, but I was using an older image. Sorry! Works just fine!

**Pull request merged**
