### PR TITLE
[mp] Update pipeline overview screenshot

### PR DESCRIPTION
**Pull request by mattppal**
Quick PR to update the pipeline overview screenshot that appears in a few locations

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
Why do we update the screenshot?
The new image's resolution is low. And we should put sensor block at the bottom

**Comment by mattppal** [comment]
> Why do we update the screenshot? The new image's resolution is low. And we should put sensor block at the bottom

The old screenshot was really old. Just uploaded a new one

**Comment by wangxiaoyou1993** [comment]
> > Why do we update the screenshot? The new image's resolution is low. And we should put sensor block at the bottom
> 
> The old screenshot was really old. Just uploaded a new one

Can we give the blocks better names in the new screenshot like the old one?

**Comment by mattppal** [comment]
> > > Why do we update the screenshot? The new image's resolution is low. And we should put sensor block at the bottom
> > 
> > 
> > The old screenshot was really old. Just uploaded a new one
> 
> Can we give the blocks better names in the new screenshot like the old one?

Blocks & pipeline renamed :)

**Review by wangxiaoyou1993 — APPROVED** [review]

**Pull request merged**
