### PR TITLE
[jk] Include Monaco Editor in build to avoid fetching from CDN

### PR DESCRIPTION
**Pull request by johnson-mage**
# Description
- Certain users (e.g. from certain countries or regions) had issues loading the code editor (Monaco Editor) without a workaround, such as using a DNS resolver like Cloudflare's free [WARP service](https://1.1.1.1/), due to a network issue fetching the editor from the jsDelivr CDN, which is the default CDN used for the [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react) package.
- [Github issue](https://github.com/mage-ai/mage-ai/issues/2776) that was created by a user, but was resolved by using the Cloudflare WARP workaround.
- In order to avoid this issue in the future, we are including the `monaco-editor` package inside the Mage build via the [method](https://github.com/suren-atoyan/monaco-react/issues/168#issuecomment-762336713) suggested by Suren Atoyan (creator of the `Monaco Editor for React ` package), where we include it as a [static asset](https://nextjs.org/docs/app/building-your-application/optimizing/static-assets) in the `public` directory.

# How Has This Been Tested?
- Tested by exporting production build locally (running `yarn export_prod` and running app on http://localhost:6789)
- Ran performance tests (Lighthouse reports and compared Monaco Editor network request load times) to check for any significant slowdowns. There was no change in the Lighthouse performance score when loading the Pipeline Editor page using the the Monaco Editor from the CDN versus loading as a static asset, and also no increase in network request load times for the Monaco Editor.

Network requests when loading Monaco Editor from CDN:
load editor from cdn (prod build)2
Network requests when loading Monaco Editor as a static asset (payload size increased, but load times did not increase):
load editor from public (prod build)2

Before (When loading Pipeline Editor page, editor requests in Chrome's "Network" tab can be seen being sent to the CDN `https://cdn.jsdelivr.net/`):
BEFORE - load editor WITH cdn

After (no requests to jsDelivr CDN or any other CDN found when loading Pipeline Editor page, since the Monaco Editor was included as a static asset in the Mage frontend build):
AFTER - load editor without cdn

# Checklist
- [X] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [X] I have performed a self-review of my own code
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] If new documentation has been added, relative paths have been added to the appropriate section of `docs/mint.json`

### CODE REVIEW

**Review by dy46 — APPROVED** [review]

**Comment by johnson-mage** [comment]
No changes to app performance

**Comment by farmboy-dev** [comment]
Thank you so much!

**Comment by hugabora** [comment]
Hi Team,

The newest release is not running correctly w MAGE_BASE_PATH set.
The monaco editor loader.js is not rebased and hence not found, not loaded

I start my server:
  MAGE_BASE_PATH=mage ./scripts/dev.sh
page is trying to load from: http://localhost:6789/monaco-editor/min/vs/loader.js
correct location is:               http://localhost:6789/mage/monaco-editor/min/vs/loader.js

fyi @johnson-mage

**Comment by dy46** [comment]
hey @hugabora i'm taking a look into this. thanks for letting us know

**Comment by farmboy-dev** [comment]
> Hi Team,
> 
> The newest release is not running correctly w MAGE_BASE_PATH set. The monaco editor loader.js is not rebased and hence not found, not loaded
> 
> I start my server: MAGE_BASE_PATH=mage ./scripts/dev.sh page is trying to load from: http://localhost:6789/monaco-editor/min/vs/loader.js correct location is: http://localhost:6789/mage/monaco-editor/min/vs/loader.js
> 
> fyi @johnson-mage

Facing the same issue +1

**Comment by hugabora** [comment]
They fixed it already: https://github.com/mage-ai/mage-ai/pull/4012

**Pull request merged**
