### PR TITLE
[sk] Updated README with badges and new screenshots

### PR DESCRIPTION
**Pull request by skunichetty**
# Summary
Updated README with screenshots of the new UI and added badges. Also added link to licensing file.

cc:
@tommydangerous @wangxiaoyou1993

### CODE REVIEW

**Comment by johnson-mage** [comment]
@skunichetty whjere did u get the screens from? i see some outdated UI things like the old new action button

**Comment by skunichetty** [comment]
I rebuilt from master, maybe some of the newer features didn't appear. I'll take look and update.

**Comment by wangxiaoyou1993** [comment]
The text in the screenshot is too small. I can hardly read them.

**Comment by johnson-mage** [comment]
@skunichetty these file sizes are also quite large. please compress them if possible. Kai may be able to help with that if you need.

**Comment by skunichetty** [comment]
Three updates:
- I updated the screenshots with the latest build info and compressed them (they are 300-400 KB each now, can't seem to compress them too much further)
- I've also increased the font size so the text is more visible.
- I've added a badge that allows directly opening our sample notebook in Google Colab
Let me know if you think any other changes need to be made

**Review by wangxiaoyou1993 — APPROVED** [review]

**Pull request merged**
