### PR TITLE
Improved Slack notification design

### PR DESCRIPTION
**Pull request by hanslemm**
# Description

This PR improves the Slack Notification layout using Slack API Blocks.

# How Has This Been Tested?
I've created a standard "example" project (mage init + mage start) with a Slack connection.

I also supplied an example formated Slack message to the project metadata, as follows:
```yaml
notification_config:
  alert_on:
    - trigger_failure
    - trigger_passed_sla
  message_templates:
    failure:
      title: ":x:  Failed to execute pipeline {pipeline_uuid}"
      details: >
        *Execution time*: {execution_time}\n
        *Pipeline URL*: {pipeline_run_url}\n
        *Trigger name*: {pipeline_schedule_name}\n
  slack_config:
    webhook_url: "{{ env_var('SLACK_WEBHOOK_URL') }}"
```

Then I created a pipeline that raises a `ValueError` on purpose to trigger the Slack notification on failure.

The Slack notification output:
image

Note: I've added `title` as a variable to be used in Slack notifications, similar to emails.

cc: @wangxiaoyou1993

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
Have you tested this feature?

**Comment by hanslemm** [comment]
Hi, not yet! Testing.

**Comment by hanslemm** [comment]
@wangxiaoyou1993 updated the PR description

**Review by wangxiaoyou1993 — APPROVED** [review]
Thank you for improving the slack notification!

**Pull request merged**
