### PR TITLE
Upgrade nkeys to 0.2.0

### PR DESCRIPTION
**Pull request by VDuda**
# Description
I've built an custom Docker Image for python 3.12, as per that process I uncovered that mage is using an extremely deprecated package of nkeys. Highlighted here, https://github.com/nats-io/nats.py/issues/509 

nats-py[nkeys] has a dependency on ed25519, which errors on install:
```
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```
This is because ed25519 uses versioneer, which https://github.com/python-versioneer/python-versioneer/issues/375. There is https://github.com/warner/python-ed25519/issues/20 against ed25519, but it seems to be a dead project.

# How Has This Been Tested?

- [x] Docker Image py3.10 bumped version of nkeys to 2.0 in setup and requirements (builds & runs)
- [x] Docker Image py3.10 bumped version of nkeys to 2.0 in setup and requirements (builds)

# Checklist
- [ ] The PR is tagged with proper labels (bug, enhancement, feature, documentation)
- [ ] I have performed a self-review of my own code
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

cc:

@tommydangerous @wangxiaoyou1993

### CODE REVIEW

**Comment by csharplus** [comment]
@VDuda the relevant changes have been included in https://github.com/mage-ai/mage-ai/pull/5393. Please try it out and see if it works for you.

**Comment by VDuda** [comment]
@csharplus Just had a chance to review - noticed the merge with the fix for 3.12 (using nkeys 0.2.0). How come we're staying with 0.1.0 for <3.12 when nkeys should be bumped to 0.2.0 across all python versions as the 0.1.0 nkeys package maintainer even recommends bumping. This would also increase performance when signing by 20x apparently - but not too sure how often this function gets called for signing.  

https://github.com/warner/python-ed25519/blob/master/README.md 
```
...
"nkeys~=0.1.0; python_version < '3.12'",
...
```

**Comment by csharplus** [comment]
> @csharplus Just had a chance to review - noticed the merge with the fix for 3.12 (using nkeys 0.2.0). How come we're staying with 0.1.0 for <3.12 when nkeys should be bumped to 0.2.0 across all python versions as the 0.1.0 nkeys package maintainer even recommends bumping. This would also increase performance when signing by 20x apparently - but not too sure how often this function gets called for signing.
> 
> https://github.com/warner/python-ed25519/blob/master/README.md
> 
> ```
> ...
> "nkeys~=0.1.0; python_version < '3.12'",
> ...
> ```

@VDuda is nkeys `0.2.0` fully backward compatible with `0.1.0` (i.e., no breaking interfaces)? If so, we'll try bump it up for Python versions.

**Comment by VDuda** [comment]
I believe nkeys is a dependency of several of the ML packages within requirements.txt - there were a few breaking changes around oracle and duckdb I believe, but upgrading those packages should resolve it 

Here's a diff of requirements.txt with the packages I had to comment out to get the build work on my end - and it's currently what we're using. 
```
-duckdb==0.9.2
+# duckdb==0.9.2
 google-api-core~=2.15.0
 google-api-python-client~=2.70.0
 google-cloud-bigquery~=3.14.1
@@ -77,13 +77,13 @@ opentelemetry-exporter-prometheus==0.43b0
 opentelemetry-instrumentation-tornado==0.43b0
 opentelemetry-exporter-otlp==1.22.0
 opentelemetry-instrumentation-sqlalchemy==0.43b0
-oracledb==1.3.1
+oracledb==2.0.0
 pinotdb==5.1.0
 prometheus_client>=0.18.0
 psycopg2==2.9.3
 psycopg2-binary==2.9.3
 pydruid==0.6.5
-pyodbc==4.0.35
+pyodbc==5.0.0
 redshift-connector==2.0.915
 lxml==4.9.4
 snowflake-connector-python==3.5.0
@@ -115,7 +115,7 @@ stomp.py==8.1.0
 dbt-bigquery==1.7.2
 dbt-clickhouse==1.7.1
 dbt-core==1.7.4
-dbt-duckdb==1.7.0
+# dbt-duckdb==1.7.0
```

**Comment by csharplus** [comment]
> I believe nkeys is a dependency of several of the ML packages within requirements.txt - there were a few breaking changes around oracle and duckdb I believe, but upgrading those packages should resolve it
> 
> Here's a diff of requirements.txt with the packages I had to comment out to get the build work on my end - and it's currently what we're using.
> 
> ```
> -duckdb==0.9.2
> +# duckdb==0.9.2
>  google-api-core~=2.15.0
>  google-api-python-client~=2.70.0
>  google-cloud-bigquery~=3.14.1
> @@ -77,13 +77,13 @@ opentelemetry-exporter-prometheus==0.43b0
>  opentelemetry-instrumentation-tornado==0.43b0
>  opentelemetry-exporter-otlp==1.22.0
>  opentelemetry-instrumentation-sqlalchemy==0.43b0
> -oracledb==1.3.1
> +oracledb==2.0.0
>  pinotdb==5.1.0
>  prometheus_client>=0.18.0
>  psycopg2==2.9.3
>  psycopg2-binary==2.9.3
>  pydruid==0.6.5
> -pyodbc==4.0.35
> +pyodbc==5.0.0
>  redshift-connector==2.0.915
>  lxml==4.9.4
>  snowflake-connector-python==3.5.0
> @@ -115,7 +115,7 @@ stomp.py==8.1.0
>  dbt-bigquery==1.7.2
>  dbt-clickhouse==1.7.1
>  dbt-core==1.7.4
> -dbt-duckdb==1.7.0
> +# dbt-duckdb==1.7.0
> ```

Version changes for other dependent modules could potentially have unexpected impacts on users running these modules in production. Therefore, we approach updating multiple module versions with caution. We’re glad to hear you’ve found a workaround for this version upgrade.

**Comment by csharplus** [comment]
@VDuda the suggested change has been merged with https://github.com/mage-ai/mage-ai/pull/5604.

**Pull request closed without merging**
