### PR TITLE
[dy] Add initial datadog logging library

### PR DESCRIPTION
**Pull request by dy46**
# Summary

Add some basic datadog logging methods. Not entirely sure what the difference is between using the api and the `statsd` library.

# Tests

tested locally
Screenshot 2023-02-23 at 12 17 56 PM

cc: @wangxiaoyou1993

### CODE REVIEW

**Comment by wangxiaoyou1993** [comment]
You'll need to run a datadog agent to use statsd

**Comment by dy46** [comment]
@wangxiaoyou1993 should we just default to using the api then?

**Comment by dy46** [comment]
@wangxiaoyou1993 PTAL

**Review by wangxiaoyou1993 — APPROVED** [review]

**Comment by wangxiaoyou1993** [comment]
Could you add unit tests?

**Comment by dy46** [comment]
yeah i'll do it in another pr

**Pull request merged**
