### PR TITLE
[sp] column view backend integration

### PR DESCRIPTION
**Pull request by shrey-mage**
# Summary
- see above
- update styling to be closer to Figma

# Tests
image

This PR will not work until Nathaniel's bugfix (#73) is merged as well, since that affects the dataset view used to get to this page.

In addition, the bug where NextJS's router doesn't allow direct paths affects this page too, so accessing /datasets/[id]/features directly does not work and causes an error. If there's a fix please let me know

cc: @johnson-mage @nathaniel-mage

### CODE REVIEW

**Comment by nathaniel-mage** [comment]
I saw that you mentioned #73, how is the metrics table blocking the PR? Not sure if I'm missing something.

**Comment by shrey-mage** [comment]
> I saw that you mentioned #73, how is the metrics table blocking the PR? Not sure if I'm missing something.

It's not blocking, we just can't test the column view independently without your bugfix to the infinite rerender issue on the dataset view, because you can't directly access the /features page because of the NextJS routing bug. I tested it locally by making the change you sent, but I didn't want to recommit that, so I removed that before pushing this PR.

**Review by nathaniel-mage — COMMENTED** [review]
Is it possible to remove updating the out files from this commit? I have another one pending that removes all out files and I think this could cause issues.

**Comment by shrey-mage** [comment]
Oh yeah I didn't mean to add out files to this commit, don't know why it's in there. I'll try to remove that

**Review by nathaniel-mage — APPROVED** [review]
Looks good.

**Pull request merged**
